spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres:5432/users_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  output:
    ansi:
      enabled: always

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always